name: Code Analysis

on:
  pull_request: null
  push:
    branches:
      - main

permissions:
  contents: read

env:
  COMPOSER_CACHE_DIR: /tmp/composer-cache

jobs:
  rector_analysis:
    name: Rector analysis
    runs-on: ubuntu-latest
    env:
      PHP_VERSION: 8.4
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - uses: shivammathur/setup-php@b604ade2a87db23f8871b7182e69ec5e75effb45 # v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: json, mbstring, pdo, curl, pdo_sqlite
          coverage: none
          tools: symfony-cli
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Composer dependencies
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: ${{ env.COMPOSER_CACHE_DIR }}
          key: ${{ runner.os }}-${{ matrix.php-version }}-${{ hashFiles('**/composer.json') }}
      - run: composer install --no-progress --no-interaction

      - run: vendor/bin/rector process -n --no-progress-bar --ansi

  code_analysis:
    strategy:
      fail-fast: false
      matrix:
        php-version: [ '8.2', '8.3', '8.4' ]
        actions:
          - name: Coding Standard
            # tip: add "--ansi" to commands in CI to make them full of colors
            run: vendor/bin/ecs check src --ansi

          - name: PHPStan
            run: vendor/bin/phpstan analyse --ansi

          - name: Check composer.json and composer.lock
            run: composer validate --strict --ansi

    name: ${{ matrix.actions.name }} - PHP ${{ matrix.php-version }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      # see https://github.com/shivammathur/setup-php
      - uses: shivammathur/setup-php@b604ade2a87db23f8871b7182e69ec5e75effb45 # v2
        with:
          # test the lowest version, to make sure checks pass on it
          php-version: ${{ matrix.php-version }}
          extensions: json, mbstring, pdo, curl, pdo_sqlite
          coverage: none
          tools: symfony-cli
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Composer dependencies
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ matrix.php-version }}-${{ hashFiles('**/composer.json') }}
      - uses: php-actions/composer@8a65f0d3c6a1d17ca4800491a40b5756a4c164f3 # v6
        with:
          php_version: ${{ matrix.php-version }}

      - run: ${{ matrix.actions.run }}
